version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file lambda-deployment/samTemplate.yaml --s3-bucket praffuln-lambda-pipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml