version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samchapter-5"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1f7qodinezbqw"
s3_prefix = "samchapter-5"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
